# This script can be used to label the 3D point cloud (e.g. '.nvm' files generated by SfM techniques such as Bundler of Visual SFM) using the coresponding 2D labeled reference images.

from PIL import Image

with open('123.nvm', 'r') as file:      # Change the file name to the one you want to process
    data = file.readlines()
for i in range(44,3125):                # Change the 3D points line range according to your '.nvm' file
    # Find which image the 3D point was seen
    imgIndex = data[i].split()[7]
    imgName = imgIndex + '.png'
    image2d = Image.open(imgName)
    # Find the 2D location of the 3D point 
    x_value = 240 + int(float(data[i].split()[9]))
    y_value = 180 - int(float(data[i].split()[10]))
    # Get the RGB value (predefined semantic label) at that location
    r, g, b = image2d.getpixel((x_value, y_value))
    # Propogate the label to 3D
    R = [str(r)]
    G = [str(g)]
    B = [str(b)]
    newlinelist = data[i].split()[:3] + R + G + B +data[i].split()[6:]
    newline = ' '.join(newlinelist)
    data[i] = newline + '\n'
# Save the file
with open('123.nvm', 'w') as file:
    file.writelines(data)
